title: Giusy – Financial Analyst
description: Quantitative Finance ·Risk Management· Rough Volatility Models · Machine Learning and AI
theme: jekyll-theme-minimal

# Add this to include custom stylesheet
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

# Custom style
defaults:
  -
    scope:
      path: ""
    values:
      css: "main/style.css"
