title: "Giusy – Financial Analyst"
description: "Quantitative Finance · Risk Management · Rough Volatility Models · Machine Learning & AI"
theme: jekyll-theme-slate

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

header_pages:
  - index.md
  - projects.md
  - resume.md
  - contact.md
