title: "Giusy – Financial Analyst"
description: "Quantitative Finance · Risk Management · Rough Volatility Models · Machine Learning & AI"
theme: jekyll-theme-slate-day

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed

# Custom defaults
defaults:
  -
    scope:
      path: ""
    values:
      css:

# Navigation bar
header_pages:
  - index.md
  - projects.md
  - resume.md
  - contact.md
